---
title: "PLA"
author: "yida"
date: "2019/8/26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Perceptron Hypothesis Set 
$$x = (x_1, ..., x_d)$$
$$h(x) = sign((\sum_{i=1}^{d} w_{i}*x{i} - threshold ))$$    

>  Perceptron Learning Alogithm pseudocode  
P <- input with label 1  
N <- inputs with label 0  
Initialize w randomly  
while !cinvergence do  
  case 1: when x belong to P & w.x<0  
  	then w= w+x   
  	#increase w to get higher w.x  
  case 2: when x belong to N & w.x>0  
  	then w= w-x   
  	#Decrease w to get higher w.x  

```{r, echo=TRUE}
#functionality: generate a random dataset
#input: n - data size
#       dim - number of dimension
#       threshold - vaiation allowed
#output: list(data, coefficient of data generated)
random_data_generate <- function(n, dim, threshold){
  data <- runif(n*dim)
  data <- matrix(data, ncol= dim)
  #data[,ncol(data)] <- -data[,ncol(data)]
  coe <- runif(dim)
  label <- ifelse(data %*% coe < threshold, 1, -1 )
  #browser()
  return(list(cbind(data,  label), coe))
}
classify <- function(x, w){
  return (sign(x %*% w))
}

PLA <- function(data,threshold){
  #$$h(x) = sign((\sum_{i=1}^{d} w_{i}*x{i} - threshold ))$$
  w <- c(-threshold, runif(ncol(data)-1))
  n <- nrow(data)
  label <- data[, ncol(data)]
  value <- data[,1:ncol(data)-1]
  c <- rep(1,n)
  value <- cbind(c,value)
  update <- 0
  non_classfied <- TRUE
  #browser()
  while (non_classfied){
    non_classfied <- FALSE
    for (i in 1:n){
      if (label[i] * classify(value[i,], w) <= 0){
        update <- update + 1
        w <- w + label[i] * value[i, ]
        non_classfied <- TRUE
      }
    }
  }
  output <- list(w,update)
  return(output)
}
data_plot <- function(data,coe,threshold){
plot(data[,1:2],xlab = "x1", ylab = "x2",
     pch = ifelse(data[,3]== 1, 2, 10),
     col = ifelse(data[,3]== 1, "red", "blue")
     )
abline(threshold/coe[2], -coe[1]/coe[2])
}
PLA_plot <- function(data, coe,threshold, w){
  plot(data[,1:2],xlab = "x1", ylab = "x2",
     pch = ifelse(data[,3]== 1, 2, 10),
     col = ifelse(data[,3]== 1, "red", "blue")
  )
  abline(threshold/coe[2], -coe[1]/coe[2])
  abline((-w[1])/w[3], -w[2]/w[3],col="red")
  
}
```
 
```{r, echo=TRUE}
set.seed(98)
threshold <- 0.8
output <- random_data_generate(20, 2, threshold)
data <- output[[1]]
coe <- output[[2]]
data_plot(data, coe, threshold)
```

```{r, echo=TRUE}
threshold <- 0
output <- PLA(data, threshold)
w <- unlist(output[1])
update <- unlist(output[2])
PLA_plot(data, coe,0.8, w)
cat("Number of updates take : " , update)
```
  
```{r, echo=TRUE}
set.seed(0809)
threshold <- 0.8
output <- random_data_generate(20, 2, threshold)
data <- output[[1]]
coe <- output[[2]]
#data_plot(data, coe, threshold)
threshold <- 0
output <- PLA(data, threshold)
w <- unlist(output[1])
update <- unlist(output[2])
PLA_plot(data, coe,0.8, w)
cat("Number of updates take : " , update)
```

```{r, echo=TRUE}
set.seed(98)
threshold <- 0.8
output <- random_data_generate(100, 2, threshold)
data <- output[[1]]
coe <- output[[2]]
#data_plot(data, coe, threshold)
threshold <- 0
output <- PLA(data, threshold)
w <- unlist(output[1])
update <- unlist(output[2])
PLA_plot(data, coe,0.8, w)
cat("Number of updates take : " , update)
```

```{r, echo=TRUE}
set.seed(0618)
threshold <- 0.1
output <- random_data_generate(1000, 2, threshold)
data <- output[[1]]
coe <- output[[2]]
#data_plot(data, coe, threshold)
threshold <- 0
output <- PLA(data, threshold)
w <- unlist(output[1])
update <- unlist(output[2])
PLA_plot(data, coe,0.1, w)
cat("Number of updates take : " , update)
```
 
```{r, echo=TRUE}
set.seed(0618)
threshold <- 2.8
output <- random_data_generate(1000, 10, threshold)
data <- output[[1]]
coe <- output[[2]]
#table(data[,ncol(data)])
threshold <- 0
output <- PLA(data, threshold)
w <- unlist(output[1])
update <- unlist(output[2])
cat("Number of updates take : " , update)
#accuracy<- mean((data %*% w))
```
